on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
name: Website
jobs:
  website:
    runs-on: ubuntu-latest
    name: Website
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        run: |
          LATEST=$(find ./results/* -type d -prune | tail -n 1)
          yarn
          # this create a report.json to build the website
          # also copies html reports to www/public
          node src/report
          cd www
          yarn
          CI=false yarn build
          touch build/.nojekyll

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: www/build
